[project]
name = "celestegym"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.8.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "posix-ipc>=1.3.2",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
